### ISSUE TITLE
Missing self.thread object. should be self._thread

### ISSUE THREAD

**Issue by antonizoon** [bibanon/py8chan#10]
```
2018-11-19 13:48:30,888 - INFO - f.grab_board_py8ch.py - ln.272 - post=<Post /pol/12467804#12467804, has_file: True, has_extra_files: False>
2018-11-19 13:48:30,891 - CRITICAL - f.grab_board_py8ch.py - ln.461 - Unhandled exception!
2018-11-19 13:48:30,891 - ERROR - f.grab_board_py8ch.py - ln.462 - 'Post' object has no attribute 'thread'
Traceback (most recent call last):
  File "grab_board_py8ch.py", line 458, in <module>
    main()
  File "grab_board_py8ch.py", line 450, in main
    dev()
  File "grab_board_py8ch.py", line 435, in dev
    Files=Files,
  File "grab_board_py8ch.py", line 285, in insert_thread
    p_is_op = post.is_op,
  File "C:\Python27\lib\site-packages\py8chan\post.py", line 50, in is_op
    return self == self.thread.topic
AttributeError: 'Post' object has no attribute 'thread'
```

**Comment by antonizoon** [comment]
fixed in v0.0.3 https://github.com/bibanon/py8chan/commit/2efb7625cfb4545da089df8de8debcb7ba23b6aa
