### ISSUE TITLE
Repo Example code not working

### ISSUE THREAD

**Issue by WarmBuns** [bibanon/py8chan#21]
Not sure if 8chan broke their API or it is just on my end, but the code from the README.md

```
import py8chan
board = py8chan.Board('v')
thread = board.get_thread(423491034)

print(thread)

# supports displaying extra files in one post as well!
for file in thread.file_objects():
    print(file.file_url)

# In a while...
print("I fetched", thread.update(), "new replies.")
```

returns this error:
```
Traceback (most recent call last):
  File "8chan_crawler.py", line 2, in <module>
    board = py8chan.Board('v')
  File "/home/anto/.local/lib/python3.8/site-packages/py8chan/board.py", line 111, in __init__
    self._uri = self._get_metadata('uri')
  File "/home/anto/.local/lib/python3.8/site-packages/py8chan/board.py", line 124, in _get_metadata
    return _get_board_metadata(url_generator=self._url, board=self._board_name, key=key)
  File "/home/anto/.local/lib/python3.8/site-packages/py8chan/board.py", line 46, in _get_board_metadata
    _fetch_boards_metadata(url_generator)
  File "/home/anto/.local/lib/python3.8/site-packages/py8chan/board.py", line 34, in _fetch_boards_metadata
    boards_list = resp.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Tested on Windows 10, & Ubuntu 20.04
Python 3.8 on both

**Comment by antonizoon** [comment]
Well i dunno, hopefully someone can make a pull request to merge in.

**Comment by KebabLord** [comment]
Nope, everything just works well.
![2020-11-25_15-32](https://user-images.githubusercontent.com/24779257/100228394-aac7f200-2f33-11eb-8ab3-d0d2d4ac19a1.png)

the only reason you got that error is that thread in 3rd line `board.get_thread(423491034)`  is just deleted from board. you should been updated the thread id with something recent before running the script.

**Comment by KebabLord** [comment]
closing as it's fixed (the problem was on 8kun's side)
